'use client';
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useUser } from '../../components/session';
import { request } from '../../lib/api';
export default function Settings(){
 const user=useUser();const [page,setPage]=useState(0);const [timezone,setTimezone]=useState<string|null>(null);const [message,setMessage]=useState('');
 const history=useQuery({queryKey:['notifications',page],queryFn:()=>request<{id:string;event_type:string;title:string;status:string}[]>(`/api/v1/me/notifications?page=${page}`),enabled:!!user});
 return <main className="shell"><h1 className="text-3xl font-semibold mb-8">A little about you</h1>{user?<><section className="card"><h2 className="text-xl font-semibold">{user.firstName}</h2><p className="muted mt-2">Signed in through Telegram</p><form className="mt-6" onSubmit={async e=>{e.preventDefault();try{await request('/api/v1/me',{method:'PATCH',body:JSON.stringify({timezone:timezone??user.timezone})});setMessage('Timezone saved.');}catch(e){setMessage((e as Error).message);}}}><label htmlFor="timezone">Your timezone</label><input id="timezone" className="field mt-2" value={timezone??user.timezone} onChange={e=>setTimezone(e.target.value)} required/><button className="button mt-4">Save settings</button><p role="status" className="mt-3">{message}</p></form></section><section className="card mt-6"><h2 className="text-xl mb-3">Telegram notifications</h2><p>Start the bot in a private chat to receive changes. Choose your notification level on each event.</p>{process.env.NEXT_PUBLIC_TELEGRAM_BOT_USERNAME&&<a className="button mt-4" href={`https://t.me/${process.env.NEXT_PUBLIC_TELEGRAM_BOT_USERNAME}?start=notifications`}>Enable notifications</a>}</section><section className="mt-8"><h2 className="text-xl mb-4">Recent notifications</h2>{history.error?<p role="alert">{history.error.message}</p>:history.data?.length?history.data.map(n=><div className="card mb-3" key={n.id}><strong>{n.title}</strong><p className="text-sm mt-2">{n.event_type.toLowerCase().replaceAll('_',' ')} · {n.status.toLowerCase()}</p></div>):<p className="muted">You’re all caught up.</p>}<nav aria-label="Notification pages" className="flex gap-4 mt-4"><button disabled={page===0||history.isFetching} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page+1}</span><button disabled={history.data?.length!==30||history.isFetching} onClick={()=>setPage(page+1)}>Next</button></nav></section></>:<p>Open Gather in Telegram to view settings.</p>}</main>;
}
