'use client';
import { useState } from 'react';
import { useQuery,useQueryClient } from '@tanstack/react-query';
import { request } from '../../lib/api';
import { useUser } from '../../components/session';
type Comment={id:string;authorId:string;authorName:string;section:string;parentCommentId:string|null;body:string;deletedAt:string|null};
export function Discussion({eventId,closed}:{eventId:string;closed:boolean}) {
 const user=useUser();const cache=useQueryClient();const [page,setPage]=useState(0);const [body,setBody]=useState('');const [parent,setParent]=useState<string|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const q=useQuery({queryKey:['event',eventId,'comments','ALL',page],queryFn:()=>request<Comment[]>(`/api/v1/events/${eventId}/comments?section=ALL&page=${page}`)});
 async function mutate(path:string,method:string,data?:object){setBusy(true);setError('');try{await request(path,{method,body:data?JSON.stringify(data):undefined});await cache.invalidateQueries({queryKey:['event',eventId,'comments']});return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 return <section className="card mt-6"><h2 className="text-xl mb-4">Talk through the plan</h2>
 {q.data?.map(c=><article key={c.id} className={`border-b border-stone-200 py-4 ${c.parentCommentId?'ml-6':''}`}><p className="font-semibold">{c.authorName}{c.parentCommentId?' · reply':''}</p><p className="whitespace-pre-wrap my-2">{c.body}</p>{!closed&&!c.deletedAt&&<div className="flex gap-4 text-sm">{!c.parentCommentId&&<button onClick={()=>setParent(c.id)}>Reply</button>}{c.authorId===user?.id&&<><button onClick={()=>{const text=window.prompt('Edit your comment',c.body);if(text)void mutate(`/api/v1/comments/${c.id}`,'PATCH',{body:text});}}>Edit</button><button onClick={()=>void mutate(`/api/v1/comments/${c.id}`,'DELETE')}>Delete</button></>}</div>}</article>)}
 {q.isPending?<p role="status">Loading discussion…</p>:!q.data?.length&&!q.error?<p className="muted">No comments on this page yet.</p>:null}<nav aria-label="Discussion pages" className="flex gap-4 mt-4"><button disabled={page===0||q.isFetching} onClick={()=>{setPage(page-1);setParent(null);}}>Previous</button><span>Page {page+1}</span><button disabled={q.data?.length!==50||q.isFetching} onClick={()=>{setPage(page+1);setParent(null);}}>Next</button></nav>
 {!closed&&<form className="mt-5" onSubmit={async e=>{e.preventDefault();if(await mutate(`/api/v1/events/${eventId}/comments`,'POST',{section:parent?(q.data?.find(c=>c.id===parent)?.section??'GENERAL'):'GENERAL',parentCommentId:parent,body})){setBody('');setParent(null);}}}>{parent&&<p>Replying to a comment <button type="button" onClick={()=>setParent(null)}>Cancel reply</button></p>}<label htmlFor="comment" className="block mb-2">Add to the conversation</label><textarea className="field" id="comment" value={body} onChange={e=>setBody(e.target.value)} required maxLength={2000}/><button className="button mt-3" disabled={busy}>Post comment</button></form>}{(error||q.error)&&<p role="alert">{error||q.error?.message}</p>}</section>;
}
