'use client';
import { useRef, useState } from 'react';
import { useQuery,useQueryClient } from '@tanstack/react-query';
import { DateTime } from 'luxon';
import { request } from '../../lib/api';
import type { GatherEvent } from '../../lib/types';
type Interval={start:string;end:string};type Slot=import('../../lib/types').ScheduleSlot;
export function Scheduling({event,organizer}:{event:GatherEvent;organizer:boolean}) {
 const drag=useRef<boolean|null>(null);
 const cache=useQueryClient();const [selected,setSelected]=useState<Set<number>|null>(null);const [day,setDay]=useState(0);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const mine=useQuery({queryKey:['event',event.id,'availability'],queryFn:()=>request<{intervals:Interval[]}>(`/api/v1/events/${event.id}/availability`)});
 const ranked=useQuery({queryKey:['event',event.id,'recommendations'],queryFn:()=>request<{slots:Slot[]}>(`/api/v1/events/${event.id}/schedule-recommendations`)});
 const start=Date.parse(event.flexWindowStart!),end=Date.parse(event.flexWindowEnd!);const count=Math.floor((end-start)/1800000);
 const current=selected??new Set(Array.from({length:count},(_,i)=>i).filter(i=>mine.data?.intervals.some(r=>Date.parse(r.start)<=start+i*1800000&&Date.parse(r.end)>=start+(i+1)*1800000)));
 function paint(i:number,value:boolean){setSelected(previous=>{const next=new Set(previous??current);if(value)next.add(i);else next.delete(i);return next;});}
 function toggle(i:number){paint(i,!current.has(i));}
 async function save(){setBusy(true);setError('');const intervals:Interval[]=[];for(let i=0;i<count;i++)if(current.has(i)){const first=i;while(current.has(i+1))i++;intervals.push({start:new Date(start+first*1800000).toISOString(),end:new Date(start+(i+1)*1800000).toISOString()});}try{await request(`/api/v1/events/${event.id}/availability`,{method:'PUT',body:JSON.stringify({intervals})});await cache.invalidateQueries({queryKey:['event',event.id]});setSelected(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function finalize(slot:Slot){setBusy(true);try{await request(`/api/v1/events/${event.id}/schedule/finalize`,{method:'POST',headers:{'If-Match':`"${event.version}"`},body:JSON.stringify({start:slot.start,end:slot.end})});await cache.invalidateQueries({queryKey:['event',event.id]});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="card mt-6"><h2 className="text-xl mb-3">Find a time together</h2><p className="mb-4">{event.durationMinutes} minutes · {event.timezone}. Set Going or Maybe so your availability counts.</p>
 {event.status==='OPEN'&&<><label htmlFor="availability-day">Planning day</label><select id="availability-day" className="field mb-4" value={day} onChange={e=>setDay(Number(e.target.value))}>{Array.from({length:Math.ceil(count/48)},(_,d)=><option key={d} value={d}>{DateTime.fromMillis(start+d*48*1800000).setZone(event.timezone).toFormat('ccc LLL d HH:mm')}</option>)}</select><p className="muted mb-3">Tap or drag to select half-hour blocks. Use Tab and Space with a keyboard.</p><div className="grid grid-cols-3 gap-2" onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}>{Array.from({length:Math.min(48,count-day*48)},(_,offset)=>{const i=day*48+offset;const label=DateTime.fromMillis(start+i*1800000).setZone(event.timezone).toFormat('ccc HH:mm ZZZZ');return <button type="button" role="checkbox" key={i} aria-checked={current.has(i)} className="availability-cell border rounded-lg p-3 text-sm" onPointerDown={e=>{if(e.button!==0)return;drag.current=!current.has(i);paint(i,drag.current);}} onPointerEnter={e=>{if(e.buttons===1&&drag.current!==null)paint(i,drag.current);}} onClick={e=>{if(e.detail===0)toggle(i);}} aria-label={`Available ${label} for 30 minutes`}><span aria-hidden="true">{current.has(i)?'✓':'○'}</span> {label}</button>;})}</div><button className="button mt-4" disabled={busy||mine.isPending} onClick={()=>void save()}>Save availability</button></>}
 <h3 className="font-semibold mt-6 mb-3">Best times</h3>{ranked.data?.slots.map(slot=><div key={slot.start} className="border-t py-4"><p>{DateTime.fromISO(slot.start).setZone(event.timezone).toFormat('ccc LLL d · HH:mm')}–{DateTime.fromISO(slot.end).setZone(event.timezone).toFormat('HH:mm')}</p><p>{slot.goingAvailable} going + {slot.maybeAvailable} maybe available</p>{organizer&&event.status==='OPEN'&&<button className="button mt-2" disabled={busy} onClick={()=>void finalize(slot)}>Finalize this time</button>}</div>)}{(error||ranked.error||mine.error)&&<p role="alert">{error||ranked.error?.message||mine.error?.message}</p>}</section>;
}
